# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
