# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='User',
        ),
    ]
